export const businessProfileClfLcYearWiseSchema = {
    $schema: "fe.v1",
    id: "business-profile-clf-lc-yearwise-form",
    version: "1.0.0",
    sections: [
        {
            id: "business-profile-clf-lc-yearwise-section",
            title: "Business Profile of CLF-LCs (Year wise)",
            fields: [
                {
                    id: "district",
                    type: "autocomplete",
                    label: "District",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "districts" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "block",
                    type: "autocomplete",
                    label: "Block",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "blocks" },
                        dependsOn: ["values.district"],
                        dependsOnHint: "Select District first",
                        queryBuilder: (deps) => ({
                            type: "blocks",
                            id: deps.district,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clfLcName",
                    type: "autocomplete",
                    label: "CLF LCs Name",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "clf_profiles" },
                        dependsOn: ["values.block"],
                        dependsOnHint: "Select Block first",
                        queryBuilder: (deps) => ({
                            type: "clf_profiles",
                            id: deps.block,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "yearOfRegistration",
                    type: "text",
                    label: "Year of registration",
                    validations: [{ type: "required" }],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "registrationNumber",
                    type: "text",
                    label: "Registration Number",
                    validations: [{ type: "required" }],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "yearOfTakenInReap",
                    type: "text",
                    label: "Year of Taken in REAP",
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "totalVillageCovered",
                    type: "text",
                    label: "Total Village Covered",
                    validations: [{ type: "required" }],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                }, 
                {
                    id: "totalShg",
                    type: "text",
                    label: "Total SHG",
                    validations: [{ type: "required" }],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "shareholdersAgainstShgMembers",
                    type: "text",
                    label: "Shareholders against SHG Members",
                    validations: [{ type: "required" }],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "yearToUpdate",
                    type: "autocomplete",
                    label: "Choose Year to Update",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "financial_year" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "monthToUpdate",
                    type: "autocomplete",
                    label: "Select Month to Update",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "months" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "salesTurnoverCurrentMonth",
                    type: "text",
                    label: "Sales Turnover in the Month",
                    validations: [{ type: "required" }],
                    props: { placeholder: "Enter Sales Turnover" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "grossProfitCurrentMonth",
                    type: "text",
                    label: "Gross profit in the Month (Cumulative)",
                    validations: [{ type: "required" }],
                    props: { placeholder: "Enter Gross Profit" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "shareholdersInvolvedCurrentMonth",
                    type: "text",
                    label: "Shareholders involved in the month (Only New)",
                    validations: [{ type: "required" }],
                    props: { placeholder: "Enter Shareholders Involved" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                }

            ],
        },
    ],
};
