export const cboEnterpriseActivityUpdateSchema = {
    $schema: "fe.v1",
    id: "cbo-level-enterprise-activity-update-form",
    version: "1.0.0",
    title: "CBO Level Enterprise",
    sections: [
        {
            id: "cbo-level-enterprise",
            title: "CBO Level Enterprise",
            fields: [
                /* --- Action --- */
                {
                    id: "action",
                    type: "radio-group",
                    label: "Action",
                    defaultValue: "create",
                    options: {
                        items: [
                            { label: "Add New", value: "create" },
                            { label: "Update Existing", value: "update" },
                        ],
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },

                /* --- Category & Location Hierarchy --- */
                // {
                //     id: "categoryOfParticipants",
                //     type: "autocomplete",
                //     label: "Category of Participants",
                //     options: {
                //         endpointKey: "v1/master/data",
                //         labelKey: "name",
                //         valueKey: "id",
                //         query: { type: "category_of_participants" },
                //     },
                //     validations: [{ type: "required" }],
                //     grid: { span: { xs: 12, sm: 6, md: 4 } },
                // },
                {
                    id: "district",
                    type: "autocomplete",
                    label: "District",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "districts" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "block",
                    type: "autocomplete",
                    label: "Block",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "blocks" },
                        dependsOn: ["values.district"],
                        dependsOnHint: "Select District first",
                        queryBuilder: (deps) => ({
                            type: "blocks",
                            id: deps.district,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "gp",
                    type: "autocomplete",
                    label: "Gram Panchayat",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "panchayats" },
                        dependsOn: ["values.block"],
                        dependsOnHint: "Select Block first",
                        queryBuilder: (deps) => ({
                            type: "panchayats",
                            id: deps.block,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "village",
                    type: "autocomplete",
                    label: "Village",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "villages" },
                        dependsOn: ["values.gp"],
                        dependsOnHint: "Select Gram Panchayat first",
                        queryBuilder: (deps) => ({
                            type: "villages",
                            id: deps.gp,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clf",
                    type: "autocomplete",
                    label: "CLF",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "clf_profiles" },
                        dependsOn: ["values.block"],
                        dependsOnHint: "Select Block first",
                        queryBuilder: (deps) => ({
                            type: "clf_profiles",
                            id: deps.block,
                        }),
                    },
                    validations: [{ type: "required" }],
                    rules: [{ when: "values.action === 'update'", action: "hide" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "localId",
                    type: "autocomplete",
                    label: "Select CLF To Update",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "name",
                        valueKey: "id",
                        query: { type: "cbo_enterprise_activities" },
                        dependsOn: ["values.block"],
                        dependsOnHint: "Select Block first",
                        queryBuilder: (deps) => ({
                            type: "cbo_enterprise_activities",
                            id: deps.block,
                        }),
                    },
                    validations: [{ type: "required" }],
                    rules: [{ when: "values.action !== 'update'", action: "hide" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                /* --- Enterprise Details --- */
                {
                    id: "enterpriseType",
                    type: "autocomplete",
                    label: "Type of Enterprise",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "enterprise_type" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "currentLivelihoodActivity",
                    type: "autocomplete",
                    label: "Current Livelihood Activity",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "enterprise_type" },
                        dependsOn: ["values.enterpriseType"],
                        dependsOnHint: "Select Enterprise Type first",
                        queryBuilder: (deps) => ({
                            type: "enterprise_type",
                            id: deps.enterpriseType === "Farm Based - Individual Enterprise" ? 1 : 2,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "proposedEnterprise",
                    type: "autocomplete",
                    label: "Proposed Enterprise",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "enterprise_type" },
                        dependsOn: ["values.enterpriseType"],
                        dependsOnHint: "Select Enterprise Type first",
                        queryBuilder: (deps) => ({
                            type: "enterprise_type",
                            id: deps.enterpriseType === "Farm Based - Individual Enterprise" ? 1 : 2,
                        }),
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clfPanTan",
                    type: "text",
                    label: "CLF PAN/TAN",
                    props: { placeholder: "Enter CLF PAN/TAN" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "financeYear",
                    type: "autocomplete",
                    label: "Finance Year",
                    options: {
                        endpointKey: "v1/master/data",
                        labelKey: "label",
                        valueKey: "value",
                        query: { type: "financial_year" },
                    },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },

                /* --- Financial Details --- */
                {
                    id: "financialDetailsSection",
                    type: "subHeading",
                    label: "Project Cost Details",
                    grid: { span: { xs: 12 } },
                },
                {
                    id: "clfContribution",
                    type: "text",
                    label: "CLF Contribution (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter CLF Contribution" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "projectSupport",
                    type: "text",
                    label: "Project Support (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter Project Support" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "convergence",
                    type: "text",
                    label: "Convergence (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter Convergence" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "bank",
                    type: "text",
                    label: "Bank (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter Bank Contribution" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                }, {
                    id: "totalCost",
                    type: "text",
                    label: "Total Cost (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },

                /* ---CBO Bank Details --- */

                {
                    id: "clfBankDetails",
                    type: "subHeading",
                    label: "CLF Bank Details",
                    grid: { span: { xs: 12 } },
                },
                {
                    id: "clfBankName",
                    type: "text",
                    label: "CLF Bank Name",
                    validations: [{ type: "required" }],
                    props: { placeholder: "Enter CLF Bank Name" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clfAccountNumber",
                    type: "text",
                    label: "CLF Account Number",
                    validations: [{ type: "required" }],
                    props: { maxLength: 24, placeholder: "Enter CLF Account Number" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clfIfscCode",
                    type: "text",
                    label: "CLF IFSC Code",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^[A-Z]{4}0[A-Z0-9]{6}$",
                            message: "Invalid IFSC Code",
                        },
                    ],
                    props: { maxLength: 11, placeholder: "Enter CLF IFSC Code" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "clfMobileNumber",
                    type: "text",
                    label: "CLF Mobile Number",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^[6-9]\\d{9}$",
                            message: "Enter valid 10-digit mobile number",
                        },
                    ],
                    props: { maxLength: 10, placeholder: "Enter CLF Mobile Number" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                /* --- Fund Received Details --- */
                {
                    id: "fundReceivedDetails",
                    type: "subHeading",
                    label: "Fund Received Details",
                    grid: { span: { xs: 12 } },
                },
                {
                    id: "fundReceivedDate",
                    type: "date",
                    label: "Fund Received Date",
                    validations: [{ type: "required" }],
                    props: { format: "DD/MM/YYYY" },
                    config: {
                        valueKind: "iso",
                        outputFormat: "YYYY-MM-DD",
                        disableFuture: true,
                    },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "fundLcfContribution",
                    type: "text",
                    label: "Fund LCF Contribution (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter LCF Contribution" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "fundProjectSupport",
                    type: "text",
                    label: "Fund Project Support (₹)",
                    validations: [{ type: "required" },
                    {
                        type: "pattern",
                        value: "^\\d+$",
                        message: "Invalid Input, Expecting Number",
                    },
                    ],
                    props: { placeholder: "Enter Project Support" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "fundConvergence",
                    type: "text",
                    label: "Fund Convergence (₹)",
                    validations: [
                        { type: "required" }
                        ,
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { placeholder: "Enter Convergence" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "fundBank",
                    type: "text",
                    label: "Fund Bank (₹)",
                    validations: [{ type: "required" },
                    {
                        type: "pattern",
                        value: "^\\d+$",
                        message: "Invalid Input, Expecting Number",
                    },
                    ],
                    props: { placeholder: "Enter Bank Contribution" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "fundTotalCost",
                    type: "text",
                    label: "Total Cost (₹)",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    rules: [{ when: "true", action: "disable" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },

                /* --- CLF Bank Loan Account Details --- */
                {
                    id: "clfBankLoanAccountDetails",
                    type: "subHeading",
                    label: "CLF Bank Loan Account Details",
                    grid: { span: { xs: 12 } },
                },
                {
                    id: "loanBankName",
                    type: "text",
                    label: "CLF Loan Bank Name",
                    validations: [{ type: "required" }],
                    props: { placeholder: "Enter CLF Loan Bank Name" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "loanBankAccount",
                    type: "text",
                    label: "CLF Loan A/C",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^\\d+$",
                            message: "Invalid Input, Expecting Number",
                        },
                    ],
                    props: { maxLength: 24, placeholder: "Enter CLF Loan A/C" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "loanBankIfcs",
                    type: "text",
                    label: "CLF Loan IFSC Code",
                    validations: [
                        { type: "required" },
                        {
                            type: "pattern",
                            value: "^[A-Z]{4}0[A-Z0-9]{6}$",
                            message: "Invalid IFSC",
                        },
                    ],
                    props: { maxLength: 11, placeholder: "Enter CLF IFSC Code" },
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                /* --- Uploads --- */
                {
                    id: "fileUploads",
                    type: "subHeading",
                    label: "File Uploads (Upload all relevant documents)",
                    grid: { span: { xs: 12 } },
                },
                {
                    id: "uploadProposal",
                    type: "file",
                    label: "Upload Proposal (PDF)",
                    props: { accept: ".pdf" },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "enterpriseImage",
                    type: "file",
                    label: "Enterprise Image",
                    props: { accept: "image/*" },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
                {
                    id: "meansOfVerification",
                    type: "file",
                    label: "Means of Verification",
                    props: { accept: ".pdf,image/*" },
                    validations: [{ type: "required" }],
                    grid: { span: { xs: 12, sm: 6, md: 4 } },
                },
            ],
        },
    ],
};
