export const beneficiaryTableHeader = [
  { id: "memberId", label: "Member ID", sortable: true },
  { id: "name", label: "Name", sortable: true },
  { id: "guardianName", label: "Father/Husband Name", sortable: true },
  { id: "age", label: "Age", numeric: true, sortable: true },
  { id: "gender", label: "Gender", sortable: true },
  { id: "mobileNumber", label: "Mobile Number", sortable: true },
  { id: "shgName", label: "SHG Name", sortable: true },
];

export const dummyData = [
  {id:1,
    memberId: "M001",
    name: "Alice Johnson",
    guardianName: "Robert Johnson",
    age: 30,
    gender: "Female",
    mobileNumber: "123-456-7890",
    shgName: "Sunrise SHG",
  },
  {
    id: 2,
    memberId: "M002",
    name: "Bob Smith",
    guardianName: "Alice Smith",
    age: 40,
    gender: "Male",
    mobileNumber: "987-654-3210",
    shgName: "Sunset SHG",
  },
  {
    id: 3,
    memberId: "M003",
    name: "Charlie Brown",
    guardianName: "Lucy Brown",
    age: 25,
    gender: "Non-binary",
    mobileNumber: "555-555-5555",
    shgName: "Rising SHG",
  },
];
